# This is a notebook for Gene Ontology analysis (Over-Representation or GSEA)

```{r}

library(clusterProfiler)

organism = "org.Mm.eg.db"
#BiocManager::install(organism, character.only = TRUE)
library(organism, character.only = TRUE)

```


# Load DEG results for DRD

```{r}

data_path<-"/home/fgao/Data_RNA/Mazmanian_Lab_RNA/Henry_02232022/"

df = read.table(paste(data_path, "DEG_DRD_vs_CTRL_DESEQ2_mm10.txt", sep=""), header=TRUE, row.names=1)

# we want the log2 fold change 
original_gene_list <- df$log2FoldChange

# name the vector
names(original_gene_list) <- rownames(df)

# omit any NA values 
gene_list<-na.omit(original_gene_list)

# omit any inf values
gene_list <-gene_list[!is.infinite(gene_list)]

# sort the list in decreasing order (required for clusterProfiler)
gene_list = sort(gene_list, decreasing = TRUE)


```



# GSEA analysis for gene expression data

```{r}

gse1 <- gseGO(geneList=gene_list, 
             ont ="BP", 
             keyType = "SYMBOL", 
             nPerm = 10000, 
             minGSSize = 3, 
             maxGSSize = 800, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = organism, 
             pAdjustMethod = "none")

library(ggplot2)
plotdot1<- dotplot(gse1, showCategory=10, size=10, split=".sign") + facet_grid(.~.sign)

gse1_pos<-gse1[gse1@result$NES>0, asis=T]
gse1_neg<-gse1[gse1@result$NES<0, asis=T]

plotcnet1_pos<-cnetplot(gse1_pos, categorySize="geneNum", foldChange=gene_list, showCategory = 10)
plotcnet1_neg<-cnetplot(gse1_neg, categorySize="geneNum", foldChange=gene_list, showCategory = 10)

options(ggrepel.max.overlaps = Inf)

plotdot1
plotcnet1_pos
plotcnet1_neg

library(cowplot)
plotcnet1<-plot_grid(plotcnet1_pos, plotcnet1_neg, ncol = 2, align = 'h')

png(paste(data_path, "GO_BP_gsea_DEG_DRD_CTRL_dotplot_deseq2_BP.png", sep=""), width = 1000, height = 400)
plotdot1
dev.off()

png(paste(data_path, "GO_BP_gsea_DEG_DRD_CTRL_cnetplot_deseq2_BP.png", sep=""), width = 2000, height = 800)
plotcnet1
dev.off()

```


